import type { Metadata } from "next";
import "./globals.css";
import "./fonts/dmMono.css"
import { GoogleOAuthProvider } from "@react-oauth/google";
import { AuthProvider } from "@/components/context/authContext";
import Header from "@/components/ui/Header";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Scaffold",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
      >
        <AuthProvider>
          <GoogleOAuthProvider clientId={process.env.Google_Client_ID ||"" }>
            <Header/>
            {children}
            <Toaster position="top-right" />
          </GoogleOAuthProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
